version: '3.8'

services:
  mariadb-zh2:
    image: mariadb:10.11.3
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: Password111
      MARIADB_ROOT_PASSWORD: Password111
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d:Z
