<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="SoapMovieDataServiceService" targetNamespace="http://ws.potzh.prog4.mik.pte.hu/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://ws.potzh.prog4.mik.pte.hu/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <wsdl:types>
<xs:schema xmlns:tns="http://ws.potzh.prog4.mik.pte.hu/" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" targetNamespace="http://ws.potzh.prog4.mik.pte.hu/" version="1.0">

  <xs:element name="getMovieData" type="tns:getMovieData"/>

  <xs:element name="getMovieDataResponse" type="tns:getMovieDataResponse"/>

  <xs:complexType name="getMovieData">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="tns:movieDataRequest"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="movieDataRequest">
    <xs:sequence>
      <xs:element minOccurs="0" name="movieId" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="getMovieDataResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="return" type="tns:movieDataResponse"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="movieDataResponse">
    <xs:sequence>
      <xs:element minOccurs="0" name="imdbRating" type="xs:double"/>
      <xs:element minOccurs="0" name="movieId" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="getMovieData">
    <wsdl:part name="parameters" element="tns:getMovieData">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="getMovieDataResponse">
    <wsdl:part name="parameters" element="tns:getMovieDataResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="MovieDataService">
    <wsdl:operation name="getMovieData">
      <wsdl:input name="getMovieData" message="tns:getMovieData">
    </wsdl:input>
      <wsdl:output name="getMovieDataResponse" message="tns:getMovieDataResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="SoapMovieDataServiceServiceSoapBinding" type="tns:MovieDataService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getMovieData">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="getMovieData">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getMovieDataResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="SoapMovieDataServiceService">
    <wsdl:port name="SoapMovieDataServicePort" binding="tns:SoapMovieDataServiceServiceSoapBinding">
      <soap:address location="http://localhost:8081/potzh_ws_feladat_war_exploded/ws/movie-imdb"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
